### Registro de usuario
POST http://localhost:3000/api/user/register
Content-Type: application/json

{
  "email": "usuario10@ejemplo.com",
  "password": "miclave12345"
}

### Validación del Email
PUT http://localhost:3000/api/user/validation HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZTNlNWFiN2NiMjI0OTFjNWQ3MWY5MSIsImVtYWlsIjoidXN1YXJpbzEwQGVqZW1wbG8uY29tIiwiaWF0IjoxNzQyOTg4NzE1LCJleHAiOjE3NDM1OTM1MTV9.mMI9JmixwUmLzddknYiy7QBzJW5WY-t9StgoGJtKVgQ

{
  "code": "996151"
}