### Registro de usuario
POST http://localhost:3000/api/user/register
Content-Type: application/json

{
  "email": "final1@test.com",
  "password": "miclave12345"
}

### Verificación del código
PUT http://localhost:3000/api/user/validation
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MThiNmYyMmY3YjdlMWE0YzFiNTdhYSIsImVtYWlsIjoiZmluYWwxQHRlc3QuY29tIiwiaWF0IjoxNzQ2NDUwMTYyLCJleHAiOjE3NDcwNTQ5NjJ9.nX2svlQuYqkP4gGOsi9frHJ3gZ9DL-tCtBhj0PH7BYA

{
  "code": "985569"
}

### Login de Usuario
POST http://localhost:3000/api/user/login HTTP/1.1
Content-Type: application/json

{
  "email": "final@test.com",
  "password": "miclave12345"
}

### Actualizar datos personales (Onboarding)
PUT http://localhost:3000/api/user/onboarding
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MThhMGFmMmY3YjdlMWE0YzFiNTc5OSIsImVtYWlsIjoiZmluYWxAdGVzdC5jb20iLCJpYXQiOjE3NDY0NDQ1MzMsImV4cCI6MTc0NzA0OTMzM30.7LdFGxVLdheyMsezYs0qv_kZze8KLXuu32ERav-dtko

{
  "firstName": "PRUEBA",
  "lastName": "FINAL",
  "nif": "987654321Z"
}

### Actualizar datos de la compañía
PATCH http://localhost:3000/api/user/company HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MThhMGFmMmY3YjdlMWE0YzFiNTc5OSIsImVtYWlsIjoiZmluYWxAdGVzdC5jb20iLCJpYXQiOjE3NDY0NDQ1MzMsImV4cCI6MTc0NzA0OTMzM30.7LdFGxVLdheyMsezYs0qv_kZze8KLXuu32ERav-dtko

{
  "company": {
    "companyName": "EMPRESA FINAL S.L.",
    "companyCif": "B97654321",
    "companyAddress": "Calle Final, 123",
    "companyStreet": "FINAL V",
    "companyNumber": 33,
    "companyPostal": 28040,
    "companyCity": "Madrid",
    "companyProvince": "Madrid",
    "isAutonomous": false
  }
}

### Actualizar datos de la compañía para autónomo
PATCH http://localhost:3000/api/user/company HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MThhMGFmMmY3YjdlMWE0YzFiNTc5OSIsImVtYWlsIjoiZmluYWxAdGVzdC5jb20iLCJpYXQiOjE3NDY0NDQ1MzMsImV4cCI6MTc0NzA0OTMzM30.7LdFGxVLdheyMsezYs0qv_kZze8KLXuu32ERav-dtko

{
  "company": {
    "companyName": "EMPRESA FINAL S.L.",
    "companyCif": "B97654321",
    "companyAddress": "Calle Final, 123",
    "companyStreet": "FINAL V",
    "companyNumber": 33,
    "companyPostal": 28040,
    "companyCity": "Madrid",
    "companyProvince": "Madrid",
    "isAutonomous": true
  }
}


### Subir logo a IPFS
PATCH http://localhost:3000/api/user/logo
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MThiNmYyMmY3YjdlMWE0YzFiNTdhYSIsImVtYWlsIjoiZmluYWwxQHRlc3QuY29tIiwiaWF0IjoxNzQ2NDUwMTYyLCJleHAiOjE3NDcwNTQ5NjJ9.nX2svlQuYqkP4gGOsi9frHJ3gZ9DL-tCtBhj0PH7BYA
Content-Type: multipart/form-data; boundary=boundary123

--boundary123
Content-Disposition: form-data; name="logo"; filename="fondo.jpg"
Content-Type: image/jpeg

< ./1.jpeg
--boundary123--

### Obtener usuario desde token
GET http://localhost:3000/api/user/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MTc1YmM3OGYwZTZjOWVhM2UwZDliYiIsImVtYWlsIjoiYWRyaWFucGF6b3N2YXJlbGFAZ21haWwuY29tIiwiaWF0IjoxNzQ2MzYxNTEzLCJleHAiOjE3NDY5NjYzMTN9.0M9FhBNTcJrzwQXrEODhLhEvvIDzHbE0q1RzfUIi-D4


### Soft delete (desactivar usuario)
DELETE http://localhost:3000/api/user/delete?soft=true
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MTc1YmM3OGYwZTZjOWVhM2UwZDliYiIsImVtYWlsIjoiYWRyaWFucGF6b3N2YXJlbGFAZ21haWwuY29tIiwiaWF0IjoxNzQ2MzYxNTEzLCJleHAiOjE3NDY5NjYzMTN9.0M9FhBNTcJrzwQXrEODhLhEvvIDzHbE0q1RzfUIi-D4


### Hard delete (borrar permanentemente)
DELETE http://localhost:3000/api/user/delete?soft=false
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZTUyMTg0ZjcwZGI0ZDM4NjQ1MDU5ZiIsImVtYWlsIjoidXN1YXJpbzQxQGVqZW1wbG8uY29tIiwiaWF0IjoxNzQzNDE4ODkxLCJleHAiOjE3NDQwMjM2OTF9.AcooMy0VkQypT-bnGrEp8IA8T9pNXnbOGIW5y9SZUvM


### Enviar código de recuperación
POST http://localhost:3000/api/user/recover
Content-Type: application/json

{
  "email": "adrianpazosvarela111@ejemplo.com"
}


### Recuperar contraseña
POST http://localhost:3000/api/user/reset-password
Content-Type: application/json

{
  "email": "usuario45@ejemplo.com",
  "code": "624299",
  "newPassword": "nuevaClaveSegura123"
}


### Invitar usuario guest
POST http://localhost:3000/api/user/invite
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZWE3NjllNzBkODkxNmI1ZjI4YTE5ZCIsImVtYWlsIjoidXN1YXJpbzQ1QGVqZW1wbG8uY29tIiwiaWF0IjoxNzQzNDE5MDM4LCJleHAiOjE3NDQwMjM4Mzh9.6fZP90Nzm2lhhyOEGqx0h42Odw-ZScWZOaS7cL1kJ_8
Content-Type: application/json

{
  "email": "invitado01@ejemplo.com"
}

### Invitar guest
POST http://localhost:3000/api/user/invite
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MTg5ZmMxNjEyZGIyNDkyZDhlYmM0NyIsImVtYWlsIjoiYWRyaWFucGF6b3N2YXJlbGExMTFAZ21haWwuY29tIiwiaWF0IjoxNzQ2NDQ0MjI1LCJleHAiOjE3NDcwNDkwMjV9.aY7Tj7tGRig8QbgwMSy0uTmdl2Gfg48Ffn7LFUGLark
Content-Type: application/json

{
  "email": "invitado3@ejemplo.com"
}

### Enviar correo electrónico
POST http://localhost:3000/api/mail
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MTg5ZmMxNjEyZGIyNDkyZDhlYmM0NyIsImVtYWlsIjoiYWRyaWFucGF6b3N2YXJlbGExMTFAZ21haWwuY29tIiwiaWF0IjoxNzQ2NDQ0MjI1LCJleHAiOjE3NDcwNDkwMjV9.aY7Tj7tGRig8QbgwMSy0uTmdl2Gfg48Ffn7LFUGLark

{
  "to": "adrianpazosvarela111@gmail.com",
  "from": "pazosvarelaa@gmail.com"
}